### PR TITLE
Add plugin command to generate Rails engines

### PR DESCRIPTION
**Pull request by UnderpantsGnome**
Love this idea, but I generate quite a few engines. This adds the plugin command to handle that.

`railyard plugin my_cool_plugin --mountable`

### CODE REVIEW

**Comment by brandonweiss** [comment]
Sorry, I didn't get a notification about this. Apparently unchecking "automatic watching" in your settings applies to new repositories you create as well. Whoops!

OK, so I'm peripherally aware of engines and how they work, although I haven't played with them much. I've generally seen them included inside of existing Rails apps, but I'm guessing you would use this command outside to create a gem, that would then be included in a Rails app?

**Comment by UnderpantsGnome** [comment]
No problem, github notifications can be a bit overwhelming.

Yea, you would use `rails plugin new foo --mountable` to create a gem with Rails functionality to embed into a Rails app. Here's an example of a blog engine https://github.com/pixels-and-bits/jabe

**Comment by brandonweiss** [comment]
OK, cool. I just pushed a few fixes a moment ago, would you mind rebasing against master and then also amending the README to include the new command? Thanks!

**Comment by UnderpantsGnome** [comment]
Updated, let me know if you want any changes to the README.

**Comment by brandonweiss** [comment]
Looks good! I like that you included a separate heading for the plugin command. I think that's smart, since it's a less commonly used Rails feature.

Just two things :)
1. Can you make the heading in the README an h3 (###)? It's a sub-heading of Usage.
2. Can you add a period to the end of the sentence about the plugin command? I always forget to do that when a markdown link is at the end of the sentence.

Thanks so much!

**Comment by UnderpantsGnome** [comment]
Done and done. Yeah, I can't put a period there it'll break the URL, doesn't apply to markdown URLs.

**Pull request merged**
